from pydantic import BaseModel, Field
from typing import Optional


class ChatResponse(BaseModel):
    response_code: int = Field(
        ...,
        ge=100,
        lt=600,
        description="HTTP status code representing the result of the chat request"
    )
    session_id: str = Field(
        ...,
        description="Unique identifier for the chat session"
    )
    current_response: str = Field(
        ...,
        description="The latest reply generated by the AI chatbot"
    )
    history: Optional[list[str]] = Field(
        default=None,
        description="Optional list of the most recent N messages in the conversation"
    )
    summary: Optional[str] = Field(
        default=None,
        description="Optional condensed summary of the conversation, used to preserve context and reduce token usage"
    )
    message: Optional[str] = Field(
        default=None,
        description="Optional response message"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "response_code": 200,
                    "session_id": "12345ABC",
                    "current_response": "Ciao di quali info hai bisogno?",
                    "history": ["Ciao voglio informazioni per un mutuo",
                                "Ciao di quali info hai bisogno?",
                                "Voglio aprire un mutuo per acquistare una casa",
                                "Puoi darmi altre info sulla casa? Come il prezzo di vendita, la metratura, lo "
                                "stato energetico e soprattutto quanti soldi vuoi da noi!!"],
                    "summary": "L'utente sta chiedendo un mutuo per acquistare una casa"
                }
            ]
        }
    }
